export const ADD_CATEGORY_LOADING = 'ADD_CATEGORY_LOADING';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const GET_ALL_CATEGORIES_LOADING = 'GET_ALL_CATEGORIES_LOADING';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAILED = 'GET_ALL_CATEGORIES_FAILED';

export const UPDATE_CATEGORY_LOADING = 'UPDATE_CATEGORY_LOADING';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';

export const ACTIVE_DEACTIVE_CATEGORY_LOADING = 'ACTIVE_DEACTIVE_CATEGORY_LOADING';
export const ACTIVE_DEACTIVE_CATEGORY_SUCCESS = 'ACTIVE_DEACTIVE_CATEGORY_SUCCESS';
export const ACTIVE_DEACTIVE_CATEGORY_FAILED = 'ACTIVE_DEACTIVE_CATEGORY_FAILED';