export const ADD_PROFILE_AVATAR_LOADING = 'ADD_PROFILE_AVATAR_LOADING';
export const ADD_PROFILE_AVATAR_SUCCESS = 'ADD_PROFILE_AVATAR_SUCCESS';
export const ADD_PROFILE_AVATAR_FAILED = 'ADD_PROFILE_AVATAR_FAILED';