export const ADD_NEW_SEASON_LOADING = 'ADD_NEW_SEASON_LOADING';
export const ADD_NEW_SEASON_SUCCESS = 'ADD_NEW_SEASON_SUCCESS';
export const ADD_NEW_SEASON_ERROR = 'ADD_NEW_SEASON_ERROR';


export const GET_ALL_SEASON_LOADING = 'GET_ALL_SEASON_LOADING';
export const GET_ALL_SEASON_SUCCESS = 'GET_ALL_SEASON_SUCCESS';
export const GET_ALL_SEASON_FAILED = 'GET_ALL_SEASON_FAILED';