export const ADD_NEW_SEASON_LOADING = 'ADD_NEW_SEASON_LOADING';
export const ADD_NEW_SEASON_SUCCESS = 'ADD_NEW_SEASON_SUCCESS';
export const ADD_NEW_SEASON_ERROR = 'ADD_NEW_SEASON_ERROR';


export const GET_ALL_SEASONS_LOADING = 'GET_ALL_SEASONS_LOADING';
export const GET_ALL_SEASONS_SUCCESS = 'GET_ALL_SEASONS_SUCCESS';
export const GET_ALL_SEASONS_FAILED = 'GET_ALL_SEASONS_FAILED';

export const UPDATE_SEASON_NAME_LOADING = 'UPDATE_SEASON_NAME_LOADING';
export const UPDATE_SEASON_NAME_SUCCESS = 'UPDATE_SEASON_NAME_SUCCESS';
export const UPDATE_SEASON_NAME_FAILED = 'UPDATE_SEASON_NAME_FAILED';