export const CREATE_SERIES_LOADING = 'CREATE_SERIES_LOADING';
export const CREATE_SERIES_SUCCESS = 'CREATE_SERIES_SUCCESS';
export const CREATE_SERIES_FAILED = 'CREATE_SERIES_FAILED';

export const GET_ALL_SERIES_LOADING='GET_ALL_SERIES_LOADING'

export const GET_ALL_SERIES_SUCCESS='GET_ALL_SERIES_SUCCESS'


export const GET_ALL_SERIES_FAILED='GET_ALL_SERIES_FAILED'

