export const CREATE_SERIES_LOADING = 'CREATE_SERIES_LOADING';
export const CREATE_SERIES_SUCCESS = 'CREATE_SERIES_SUCCESS';
export const CREATE_SERIES_FAILED = 'CREATE_SERIES_FAILED';

export const GET_ALL_SERIES_LOADING='GET_ALL_SERIES_LOADING'
export const GET_ALL_SERIES_SUCCESS='GET_ALL_SERIES_SUCCESS'
export const GET_ALL_SERIES_FAILED='GET_ALL_SERIES_FAILED'

export const UPDATE_SERIES_THUMBNAIL_LOADING = 'UPDATE_SERIES_THUMBNAIL_LOADING';
export const UPDATE_SERIES_THUMBNAIL_SUCCESS = 'UPDATE_SERIES_THUMBNAIL_SUCCESS';
export const UPDATE_SERIES_THUMBNAIL_FAILED = 'UPDATE_SERIES_THUMBNAIL_FAILED';

export const UPDATE_SERIES_TRAILER_LOADING = 'UPDATE_SERIES_TRAILER_LOADING';
export const UPDATE_SERIES_TRAILER_SUCCESS = 'UPDATE_SERIES_TRAILER_SUCCESS';
export const UPDATE_SERIES_TRAILER_FAILED = 'UPDATE_SERIES_TRAILER_FAILED';

export const DEACTIVE_SERIES_LOADING = 'DEACTIVE_SERIES_LOADING';
export const DEACTIVE_SERIES_SUCCESS = 'DEACTIVE_SERIES_SUCCESS';
export const DEACTIVE_SERIES_FAILED = 'DEACTIVE_SERIES_FAILED';

