export const ADD_MOVIE_LOADING = 'ADD_MOVIE_LOADING';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILED = 'ADD_MOVIE_FAILED';

export const GET_ALL_MOVIES_LOADING = 'GET_ALL_MOVIES_LOADING';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAILED = 'GET_ALL_MOVIES_FAILED';

export const UPDATE_MOVIE_INFO_LOADING = 'UPDATE_MOVIE_INFO_LOADING';
export const UPDATE_MOVIE_INFO_SUCCESS = 'UPDATE_MOVIE_INFO_SUCCESS';
export const UPDATE_MOVIE_INFO_FAILED = 'UPDATE_MOVIE_INFO_FAILED';

export const UPDATE_MOVIE_THUMBNAIL_LOADING = 'UPDATE_MOVIE_THUMBNAIL_LOADING';
export const UPDATE_MOVIE_THUMBNAIL_SUCCESS = 'UPDATE_MOVIE_THUMBNAIL_SUCCESS';
export const UPDATE_MOVIE_THUMBNAIL_FAILED = 'UPDATE_MOVIE_THUMBNAIL_FAILED';

export const UPDATE_MOVIE_TRAILER_LOADING = 'UPDATE_MOVIE_TRAILER_LOADING';
export const UPDATE_MOVIE_TRAILER_SUCCESS = 'UPDATE_MOVIE_TRAILER_SUCCESS';
export const UPDATE_MOVIE_TRAILER_FAILED = 'UPDATE_MOVIE_TRAILER_FAILED';

export const UPDATE_MOVIE_VIDEO_LOADING = 'UPDATE_MOVIE_VIDEO_LOADING';
export const UPDATE_MOVIE_VIDEO_SUCCESS = 'UPDATE_MOVIE_VIDEO_SUCCESS';
export const UPDATE_MOVIE_VIDEO_FAILED = 'UPDATE_MOVIE_VIDEO_FAILED';

export const CHANGE_MOVIE_STATUS_LOADING = 'CHANGE_MOVIE_STATUS_LOADING';
export const CHANGE_MOVIE_STATUS_SUCCESS = 'CHANGE_MOVIE_STATUS_SUCCESS';
export const CHANGE_MOVIE_STATUS_FAILED = 'CHANGE_MOVIE_STATUS_FAILED';