export const ADD_EPISODE_LOADING = 'ADD_EPISODE_LOADING';
export const ADD_EPISODE_SUCCESS = 'ADD_EPISODE_SUCCESS';
export const ADD_EPISODE_FAILED = 'ADD_EPISODE_FAILED';

export const GET_EPISODE_BY_SEASON_ID_LOADING = 'GET_EPISODE_BY_SEASON_ID_LOADING';
export const GET_EPISODE_BY_SEASON_ID_SUCCESS = 'GET_EPISODE_BY_SEASON_ID_SUCCESS';
export const GET_EPISODE_BY_SEASON_ID_FAILED = 'GET_EPISODE_BY_SEASON_ID_FAILED';

export const UPDATE_EPISODE_THUMBNAIL_LOADING = 'UPDATE_EPISODE_THUMBNAIL_LOADING';
export const UPDATE_EPISODE_THUMBNAIL_SUCCESS = 'UPDATE_EPISODE_THUMBNAIL_SUCCESS';
export const UPDATE_EPISODE_THUMBNAIL_FAILED = 'UPDATE_EPISODE_THUMBNAIL_FAILED';

export const UPDATE_EPISODE_VIDEO_LOADING = 'UPDATE_EPISODE_VIDEO_LOADING';
export const UPDATE_EPISODE_VIDEO_SUCCESS = 'UPDATE_EPISODE_VIDEO_SUCCESS';
export const UPDATE_EPISODE_VIDEO_FAILED = 'UPDATE_EPISODE_VIDEO_FAILED';

export const CHANGE_EPISODE_STATUS_LOADING = 'CHANGE_EPISODE_STATUS_LOADING';
export const CHANGE_EPISODE_STATUS_SUCCESS = 'CHANGE_EPISODE_STATUS_SUCCESS';
export const CHANGE_EPISODE_STATUS_FAILED = 'CHANGE_EPISODE_STATUS_FAILED';

export const UPDATE_EPISODE_INFO_LOADING = 'UPDATE_EPISODE_INFO_LOADING';
export const UPDATE_EPISODE_INFO_SUCCESS = 'UPDATE_EPISODE_INFO_SUCCESS';
export const UPDATE_EPISODE_INFO_FAILED = 'UPDATE_EPISODE_INFO_FAILED';
